# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from whatsappcloudapi.models.business_profile import BusinessProfile


class Data9(object):

    """Implementation of the 'Data9' model.

    Attributes:
        business_profile (BusinessProfile): The model property of type
            BusinessProfile.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "business_profile": 'business_profile'
    }

    def __init__(self,
                 business_profile=None):
        """Constructor for the Data9 class"""

        # Initialize members of the class
        self.business_profile = business_profile 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        business_profile = BusinessProfile.from_dictionary(dictionary.get('business_profile')) if dictionary.get('business_profile') else None
        # Return an object of this model
        return cls(business_profile)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'business_profile={self.business_profile!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'business_profile={self.business_profile!s})')
