# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Video(object):

    """Implementation of the 'Video' model.

    Attributes:
        caption (str): The model property of type str.
        id (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "caption": 'caption',
        "id": 'id'
    }

    def __init__(self,
                 caption=None,
                 id=None):
        """Constructor for the Video class"""

        # Initialize members of the class
        self.caption = caption 
        self.id = id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        caption = dictionary.get("caption") if dictionary.get("caption") else None
        id = dictionary.get("id") if dictionary.get("id") else None
        # Return an object of this model
        return cls(caption,
                   id)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'caption={self.caption!r}, '
                f'id={self.id!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'caption={self.caption!s}, '
                f'id={self.id!s})')
