from . import calendar_event
from . import odoo_instance
from . import odoo_instance_module
from . import odoo_instance_process
from . import odoo_instance_window
from . import odoo_release
from . import odoo_version
from . import project_project
from . import res_partner
from . import odoo_instance_database
