# -*- coding: utf-8 -*-

"""
twilioapiexplorer

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from twilioapiexplorer.models.document import Document
from twilioapiexplorer.models.meta import Meta


class OK153(object):

    """Implementation of the 'OK153' model.

    Attributes:
        documents (List[Document]): The model property of type List[Document].
        meta (Meta): The model property of type Meta.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "documents": 'documents',
        "meta": 'meta'
    }

    def __init__(self,
                 documents=None,
                 meta=None):
        """Constructor for the OK153 class"""

        # Initialize members of the class
        self.documents = documents 
        self.meta = meta 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        documents = None
        if dictionary.get('documents') is not None:
            documents = [Document.from_dictionary(x) for x in dictionary.get('documents')]
        meta = Meta.from_dictionary(dictionary.get('meta')) if dictionary.get('meta') else None
        # Return an object of this model
        return cls(documents,
                   meta)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'documents={self.documents!r}, '
                f'meta={self.meta!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'documents={self.documents!s}, '
                f'meta={self.meta!s})')
