# -*- coding: utf-8 -*-

"""
twilioapiexplorer

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from twilioapiexplorer.models.field_value import FieldValue
from twilioapiexplorer.models.meta import Meta


class OK271(object):

    """Implementation of the 'OK271' model.

    Attributes:
        field_values (List[FieldValue]): The model property of type
            List[FieldValue].
        meta (Meta): The model property of type Meta.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "field_values": 'field_values',
        "meta": 'meta'
    }

    def __init__(self,
                 field_values=None,
                 meta=None):
        """Constructor for the OK271 class"""

        # Initialize members of the class
        self.field_values = field_values 
        self.meta = meta 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        field_values = None
        if dictionary.get('field_values') is not None:
            field_values = [FieldValue.from_dictionary(x) for x in dictionary.get('field_values')]
        meta = Meta.from_dictionary(dictionary.get('meta')) if dictionary.get('meta') else None
        # Return an object of this model
        return cls(field_values,
                   meta)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'field_values={self.field_values!r}, '
                f'meta={self.meta!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'field_values={self.field_values!s}, '
                f'meta={self.meta!s})')
