# -*- coding: utf-8 -*-

"""
googlemapsplatformcoreapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PlusCode(object):

    """Implementation of the 'PlusCode' model.

    Attributes:
        global_code (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "global_code": 'globalCode'
    }

    def __init__(self,
                 global_code=None):
        """Constructor for the PlusCode class"""

        # Initialize members of the class
        self.global_code = global_code 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        global_code = dictionary.get("globalCode") if dictionary.get("globalCode") else None
        # Return an object of this model
        return cls(global_code)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'global_code={self.global_code!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'global_code={self.global_code!s})')
