= Misc Odoo Options

The converter `ConfigConverterMisc` allow to convert environment variable related to misc odoo options to valid odoo CLI.

include::partial$misc.adoc[]


== import_partial
Use this for big data importation, if it crashes you will be able to continue at the current state.
         provide a filename to store intermediate importation states.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `IMPORT_PARTIAL` is used and expect a `bool`.

Possible cli:

* -P
* --import-partial

== pidfile
File where the server pid will be stored

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `PIDFILE` is used and expect a `Path`.

Possible cli:

* --pidfile

== unaccent
Try to enable the unaccent extension when creating new databases.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `UNACCENT` is used and expect a `bool`.

Possible cli:

* --unaccent

== without_demo
NOTE: Disable loading demo data for modules to be installed (comma-separated, use "all" for all modules).
        requires -d and -i. default is %default with `Possible cli:

* --without-demo`

The environment variable `WITHOUT_DEMO` is repeatable.
This mean a suffix can be added after an **single** `_`. For example `WITHOUT_DEMO_value`, the suffix is `value` not `_value`

The behavior depends of the value.

* If the value is "True" then the suffix is used.
* If the value is "False" then value is discard
* If the value is not a boolean (int, float, string, csv) then the suffix is taken has value.

[,shell]
----
WITHOUT_DEMO="v1,v2" # <.>
WITHOUT_DEMO_0="v0,bar" # <.>
WITHOUT_DEMO_1="1" # <.>
WITHOUT_DEMO_FOO="True" # <.>
WITHOUT_DEMO_XX="bar" # <.>
----
<.> Classic csv value
<.> csv value : don't use the suffix
<.> Not a boolean value : use the value
<.> Boolean value: The suffix `FOO` is used
<.> Not a boolean value : use the value

The result (the order is not constant) will be ["v1", "v2", "v0", "foo", "bar"].

NOTE: Like csv value, all the value are deduplicated


== stop_after_init
Stop the server after its initialization

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `STOP_AFTER_INIT` is used and expect a `bool`.

Possible cli:

* --stop-after-init

== save_config_file
Save the generated config. always true

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `SAVE_CONFIG_FILE` is used and expect a `bool`.

Possible cli:

* -s
* --save

== data_dir
Directory where to store odoo data

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DATA_DIR` is used and expect a `Path`.

Possible cli:

* -D
* --data-dir



== Other keys


=== ODOO_PATH
NOTE: Convert environ key=odoo_path to <object object at 0x78756c55d420>

The environment variable `ODOO_PATH` is used and expect a `Path`.

=== ODOO_RC
NOTE: Specify alternate config file

The environment variable `ODOO_RC` is used and expect a `Path`.

=== PIDFILE
NOTE: Auto set a pid file in `/tmp/odoo.pid` if the key equal `true`

The environment variable `PIDFILE` is used and expect a `bool`.

=== WITHOUT_DEMO
NOTE: Disable loading demo data for all modules if equal to true

The environment variable `WITHOUT_DEMO` is used and expect a `bool`.

=== ADMIN_PASSWORD
NOTE: The admin password for database management

The environment variable `ADMIN_PASSWORD` is used and expect a `str`.

=== <object object at 0x78756c55d530>
NOTE: Convert cli args=['--dev', '--shell-interface'] to <object object at 0x78756c55d420>

The environment variable `<object object at 0x78756c55d530>` is used and expect a `Any`.
