= Test Configuration

The converter `ConfigConverterTest` allow to convert environment variable related to test configuration to valid odoo CLI.

include::partial$test.adoc[]


== test_enable
Enable unit tests.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `TEST_ENABLE` is used and expect a `bool`.

Possible cli:

* --test-enable

== test_file
Launch a python test file.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `TEST_FILE` is used and expect a `str`.

Possible cli:

* --test-file

== test_tags
NOTE: Comma-separated list of specs to filter which tests to execute. enable unit tests if set.
        a filter spec has the format: [-][tag][/module][:class][.method][[params]]
        the '-' specifies if we want to include or exclude tests matching this spec.
        the tag will match tags added on a class with a @tagged decorator
        (all test classes have 'standard' and 'at_install' tags
        until explicitly removed, see the decorator documentation).
        '*' will match all tags.
        if tag is omitted on include mode, its value is 'standard'.
        if tag is omitted on exclude mode, its value is '*'.
        the module, class, and method will respectively match the module name, test class name and test method name.
        example: --test-tags :testclass.test_func,/test_module,external
        it is also possible to provide parameters to a test method that supports them
        example: --test-tags /web.test_js[mail]
        if negated, a test-tag with parameter will negate the parameter when passing it to the test
        filtering and executing the tests happens twice: right
        after each module installation/update and at the end
        of the modules loading. at each stage tests are filtered
        by --test-tags specs and additionally by dynamic specs
        'at_install' and 'post_install' correspondingly. with `Possible cli:

* --test-tags`

The environment variable `TEST_TAGS` is repeatable.
This mean a suffix can be added after an **single** `_`. For example `TEST_TAGS_value`, the suffix is `value` not `_value`

The behavior depends of the value.

* If the value is "True" then the suffix is used.
* If the value is "False" then value is discard
* If the value is not a boolean (int, float, string, csv) then the suffix is taken has value.

[,shell]
----
TEST_TAGS="v1,v2" # <.>
TEST_TAGS_0="v0,bar" # <.>
TEST_TAGS_1="1" # <.>
TEST_TAGS_FOO="True" # <.>
TEST_TAGS_XX="bar" # <.>
----
<.> Classic csv value
<.> csv value : don't use the suffix
<.> Not a boolean value : use the value
<.> Boolean value: The suffix `FOO` is used
<.> Not a boolean value : use the value

The result (the order is not constant) will be ["v1", "v2", "v0", "foo", "bar"].

NOTE: Like csv value, all the value are deduplicated




== Other keys


=== DISABLE_ODOO_TESTS
NOTE: Disable test even if test_enable or test_tags exists

The environment variable `DISABLE_ODOO_TESTS` is used and expect a `bool`.

=== <object object at 0x78756c55d530>
NOTE: Screencasts will go in dir/{db_name}/screencasts.

The environment variable `<object object at 0x78756c55d530>` is used and expect a `FFFFFFFFFFFFF`.

=== <object object at 0x78756c55d530>
NOTE: Screenshot will go in dir/{db_name}/screencasts.

The environment variable `<object object at 0x78756c55d530>` is used and expect a `FFFFFFFFFFFFF`.
