BETA_BLOCKERS_TERMS = [
    "betaxolol",
    "kerlone",
    "betoptic",
    "acebutolol",
    "sectral",
    "atenolol",
    "tenormin",
    "metoprolol",
    "metoprolol succinate",
    "toprol-xl",
    "metoprolol tartrate",
    "lopressor",
    "metoprolol succinate er",
    "metoprolol tartrate",
    "dutoprolol",
    "nebivolol",
    "bystolic",
    "bisoprolol",
    "zebeta",
    "esmolol",
    "brevibloc",
    "propranolol",
    "innopran xl",
    "inderal",
    "inderal la",
    "nadolol",
    "corgard",
    "carvedilol",
    "coreg",
    "coreg cr",
    "labetalol",
    "normodyne",
    "trandate",
    "timolol",
    "blocadren",
    "timoptic",
    "istalol",
    "betimol",
    "carteolol",
    "cartrol",
    "penbutolol",
    "levatol",
    "pindolol",
    "visken",
]
