CALCIUM_CHANNEL_BLOCKERS_TERMS = [
    "amlodipine",
    "norvasc",
    "diltiazem",
    "cardizem",
    "tiazac",
    "felodipine",
    "isradipine",
    "nicardipine",
    "cardenesr",
    "cardene sr",
    "cardene-sr",
    "nifedipine",
    "procardia",
    "nisoldipine",
    "sular",
    "verapamil",
    "calan",
    "verelan",
    "covera-hs",
    "covera hs",
    "coverahs",
    "lotrel",
    "caduet",
    "bepridil",
    "vascor",
    "clevidipine",
    "cleviprex",
    "isoptin",
    "plendil",
    "lacidipine",
    "caldine",
    "lacimen",
    "lacipil",
    "midotens",
    "motens",
    "lercanidipine",
    "lercadip",
    "zanadip",
    "dynacirc",
    "adalat",
    "nifediac",
    "nifedical",
    "nimodipine",
    "nimotop",
    "prestalia",
    "teczem",
    "lexxel",
    "carmen ace",
    "coripren",
    "tarka",
    "azor",
    "tribenzor",
    "twynsta",
    "exforge",
    "exforge hct",
]
