from ..internal_utils.fallback_logger import fallback_logger as fallback_logger
from typing import Any

def get_package_info() -> dict[str, Any]: ...
def check_pypi_version(package_name: str = 'lumberjack-sdk') -> str | None: ...
def compare_versions(current: str, latest: str) -> tuple[bool, str]: ...
def generate_upgrade_command(install_info: dict[str, Any]) -> dict[str, Any]: ...
def execute_upgrade(command: str) -> dict[str, Any]: ...
def get_version_info() -> dict[str, Any]: ...
