# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from whatsappcloudapi.api_helper import APIHelper
from whatsappcloudapi.models.button_15 import Button15


class Component18(object):

    """Implementation of the 'Component18' model.

    Attributes:
        mtype (str): The model property of type str.
        text (str): The model property of type str.
        buttons (List[Button15]): The model property of type List[Button15].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": 'type',
        "text": 'text',
        "buttons": 'buttons'
    }

    _optionals = [
        'text',
        'buttons',
    ]

    def __init__(self,
                 mtype=None,
                 text=APIHelper.SKIP,
                 buttons=APIHelper.SKIP):
        """Constructor for the Component18 class"""

        # Initialize members of the class
        self.mtype = mtype 
        if text is not APIHelper.SKIP:
            self.text = text 
        if buttons is not APIHelper.SKIP:
            self.buttons = buttons 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get("type") if dictionary.get("type") else None
        text = dictionary.get("text") if dictionary.get("text") else APIHelper.SKIP
        buttons = None
        if dictionary.get('buttons') is not None:
            buttons = [Button15.from_dictionary(x) for x in dictionary.get('buttons')]
        else:
            buttons = APIHelper.SKIP
        # Return an object of this model
        return cls(mtype,
                   text,
                   buttons)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'mtype={self.mtype!r}, '
                f'text={(self.text if hasattr(self, "text") else None)!r}, '
                f'buttons={(self.buttons if hasattr(self, "buttons") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'mtype={self.mtype!s}, '
                f'text={(self.text if hasattr(self, "text") else None)!s}, '
                f'buttons={(self.buttons if hasattr(self, "buttons") else None)!s})')
