# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from whatsappcloudapi.models.data_6 import Data6


class DataPoint2(object):

    """Implementation of the 'DataPoint2' model.

    Attributes:
        timestamp (str): The model property of type str.
        data (List[Data6]): The model property of type List[Data6].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "timestamp": 'timestamp',
        "data": 'data'
    }

    def __init__(self,
                 timestamp=None,
                 data=None):
        """Constructor for the DataPoint2 class"""

        # Initialize members of the class
        self.timestamp = timestamp 
        self.data = data 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        timestamp = dictionary.get("timestamp") if dictionary.get("timestamp") else None
        data = None
        if dictionary.get('data') is not None:
            data = [Data6.from_dictionary(x) for x in dictionary.get('data')]
        # Return an object of this model
        return cls(timestamp,
                   data)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'timestamp={self.timestamp!r}, '
                f'data={self.data!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'timestamp={self.timestamp!s}, '
                f'data={self.data!s})')
