# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Reaction(object):

    """Implementation of the 'Reaction' model.

    Attributes:
        message_id (str): The model property of type str.
        emoji (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message_id": 'message_id',
        "emoji": 'emoji'
    }

    def __init__(self,
                 message_id=None,
                 emoji=None):
        """Constructor for the Reaction class"""

        # Initialize members of the class
        self.message_id = message_id 
        self.emoji = emoji 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        message_id = dictionary.get("message_id") if dictionary.get("message_id") else None
        emoji = dictionary.get("emoji") if dictionary.get("emoji") else None
        # Return an object of this model
        return cls(message_id,
                   emoji)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'message_id={self.message_id!r}, '
                f'emoji={self.emoji!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'message_id={self.message_id!s}, '
                f'emoji={self.emoji!s})')
