# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubscribeToYourWABA(object):

    """Implementation of the 'Subscribe to your WABA' model.

    Attributes:
        success (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "success": 'success'
    }

    def __init__(self,
                 success=None):
        """Constructor for the SubscribeToYourWABA class"""

        # Initialize members of the class
        self.success = success 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        success = dictionary.get("success") if dictionary.get("success") else None
        # Return an object of this model
        return cls(success)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'success={self.success!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'success={self.success!s})')
