class UserAgentException(Exception):
    pass

class LibraryLoadError(UserAgentException): ...
class InitializationError(UserAgentException): ...
class NotInitializedError(UserAgentException): ...
class BufferTooSmallError(UserAgentException): ...
class JsonMarshalError(UserAgentException): ...
class UnknownCrawlerTypeError(UserAgentException): ...