SELECT 
    BOOKMARK_END_DATE + INTERVAL '1 day' AS BOOKMARK_START_DATE,
    (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::DATE AS BOOKMARK_END_DATE
FROM 
    <DATABASE_NAME>.pybrv_meta.pybrv_metadata
WHERE 
    unique_rule_identifier = '<UNIQUE_RULE_IDENTIFIER>';
