import re
from typing import Dict, Pattern


SEARCH_PLATFORMS: Dict[str, str] = {
    'youtube music': 'ytmsearch',
    'youtubemusic': 'ytmsearch',
    'ytmsearch': 'ytmsearch',
    'ytm': 'ytmsearch',
    'musicyoutube': 'ytmsearch',
    'music youtube': 'ytmsearch',
    'youtube': 'ytsearch',
    'yt': 'ytsearch',
    'ytsearch': 'ytsearch',
    'soundcloud': 'scsearch',
    'scsearch': 'scsearch',
    'sc': 'scsearch',
    'apple music': 'amsearch',
    'apple': 'amsearch',
    'applemusic': 'amsearch',
    'amsearch': 'amsearch',
    'am': 'amsearch',
    'musicapple': 'amsearch',
    'music apple': 'amsearch',
    'spotify': 'spsearch',
    'spsearch': 'spsearch',
    'sp': 'spsearch',
    'spotify.com': 'spsearch',
    'spotifycom': 'spsearch',
    'sprec': 'sprec',
    'spsuggestion': 'sprec',
    'deezer': 'dzsearch',
    'dz': 'dzsearch',
    'dzsearch': 'dzsearch',
    'dzisrc': 'dzisrc',
    'dzrec': 'dzrec',
    'yandex music': 'ymsearch',
    'yandexmusic': 'ymsearch',
    'yandex': 'ymsearch',
    'ymsearch': 'ymsearch',
    'ymrec': 'ymrec',
    'vksearch': 'vksearch',
    'vkmusic': 'vksearch',
    'vk music': 'vksearch',
    'vkrec': 'vkrec',
    'vk': 'vksearch',
    'qbsearch': 'qbsearch',
    'qobuz': 'qbsearch',
    'qbisrc': 'qbisrc',
    'qbrec': 'qbrec',
    'speak': 'speak',
    'tts': 'tts',
    'ftts': 'ftts',
    'flowery': 'ftts',
    'flowery.tts': 'ftts',
    'flowerytts': 'ftts',
    'bandcamp': 'bcsearch',
    'bc': 'bcsearch',
    'bcsearch': 'bcsearch',
    'phsearch': 'phsearch',
    'pornhub': 'phsearch',
    'porn': 'phsearch',
    'local': 'local',
    'http': 'http',
    'https': 'https',
    'link': 'link',
    'uri': 'uri',
    'tidal': 'tdsearch',
    'td': 'tdsearch',
    'tidal music': 'tdsearch',
    'tdsearch': 'tdsearch',
    'tdrec': 'tdrec',
    'jiosaavn': 'jssearch',
    'js': 'jssearch',
    'jssearch': 'jssearch',
    'jsrec': 'jsrec'
}

LAVALINK_PLUGINS: Dict[str, str] = {
    'DuncteBot_Plugin': 'DuncteBot-plugin',
    'LavaSrc': 'lavasrc-plugin',
    'GoogleCloudTTS': 'tts-plugin',
    'LavaSearch': 'lavasearch-plugin',
    'Jiosaavn_Plugin': 'jiosaavn-plugin',
    'LavalinkFilterPlugin': 'lavalink-filter-plugin',
    'JavaTimedLyricsPlugin': 'java-lyrics-plugin'
}

SOURCE_REGEXES: Dict[str, Pattern[str]] = {
    'YoutubeRegex': re.compile(
        r'https?:\/\/?(?:www\.)?(?:(m|www)\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|shorts|playlist\?|watch\?v=|watch\?.+(?:&|&#38;);v=))([a-zA-Z0-9\-_]{11})?(?:(?:\?|&|&#38;)index=((?:\d){1,3}))?(?:(?:\?|&|&#38;)?list=([a-zA-Z\-_0-9]{34}))?(?:\S+)?'
    ),
    'YoutubeMusicRegex': re.compile(
        r'https?:\/\/?(?:www\.)?(?:(music|m|www)\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|shorts|playlist\?|watch\?v=|watch\?.+(?:&|&#38;);v=))([a-zA-Z0-9\-_]{11})?(?:(?:\?|&|&#38;)index=((?:\d){1,3}))?(?:(?:\?|&|&#38;)?list=([a-zA-Z\-_0-9]{34}))?(?:\S+)?'
    ),
    'SoundCloudRegex': re.compile(r'https:\/\/(?:on\.)?soundcloud\.com\/'),
    'SoundCloudMobileRegex': re.compile(r'https?:\/\/(soundcloud\.app\.goo\.gl)\/(\S+)'),
    'BandcampRegex': re.compile(r'https?:\/\/?(?:www\.)?([\d|\w]+)\.bandcamp\.com\/(\S+)'),
    'TwitchTvRegex': re.compile(r'https?:\/\/?(?:www\.)?twitch\.tv\/\w+'),
    'VimeoRegex': re.compile(r'https?:\/\/(www\.)?vimeo.com\/(?:channels\/(?:\w+\/)?|groups\/([^/]*)\/videos\/|)(\d+)(?:|\/\?)'),
    'Mp3UrlRegex': re.compile(r'(https?|ftp|file):\/\/(www.)?(.*?)\.(mp3)$'),
    'M3uUrlRegex': re.compile(r'(https?|ftp|file):\/\/(www.)?(.*?)\.(m3u)$'),
    'M3u8UrlRegex': re.compile(r'(https?|ftp|file):\/\/(www.)?(.*?)\.(m3u8)$'),
    'Mp4UrlRegex': re.compile(r'(https?|ftp|file):\/\/(www.)?(.*?)\.(mp4)$'),
    'M4aUrlRegex': re.compile(r'(https?|ftp|file):\/\/(www.)?(.*?)\.(m4a)$'),
    'WavUrlRegex': re.compile(r'(https?|ftp|file):\/\/(www.)?(.*?)\.(wav)$'),
    'AacpUrlRegex': re.compile(r'(https?|ftp|file):\/\/(www.)?(.*?)\.(aacp)$'),
    'DeezerTrackRegex': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?track\/(\d+)'),
    'DeezerPageLinkRegex': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.page\.link\/(\S+)'),
    'DeezerPlaylistRegex': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?playlist\/(\d+)'),
    'DeezerAlbumRegex': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?album\/(\d+)'),
    'DeezerArtistRegex': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?artist\/(\d+)'),
    'DeezerMixesRegex': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?mixes\/genre\/(\d+)'),
    'DeezerEpisodeRegex': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?episode\/(\d+)'),
    'AllDeezerRegexWithoutPageLink': re.compile(r'(https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?(track|playlist|album|artist|mixes\/genre|episode)\/(\d+)'),
    'AllDeezerRegex': re.compile(r'((https?:\/\/|)?(?:www\.)?deezer\.com\/(?:\w{2}\/)?(track|playlist|album|artist|mixes\/genre|episode)\/(\d+)|(https?:\/\/|)?(?:www\.)?deezer\.page\.link\/(\S+))'),
    'SpotifySongRegex': re.compile(r'(https?:\/\/)(www\.)?open\.spotify\.com\/((?P<region>[a-zA-Z-]+)\/)?(user\/(?P<user>[a-zA-Z0-9-_]+)\/)?track\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'SpotifyPlaylistRegex': re.compile(r'(https?:\/\/)(www\.)?open\.spotify\.com\/((?P<region>[a-zA-Z-]+)\/)?(user\/(?P<user>[a-zA-Z0-9-_]+)\/)?playlist\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'SpotifyArtistRegex': re.compile(r'(https?:\/\/)(www\.)?open\.spotify\.com\/((?P<region>[a-zA-Z-]+)\/)?(user\/(?P<user>[a-zA-Z0-9-_]+)\/)?artist\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'SpotifyEpisodeRegex': re.compile(r'(https?:\/\/)(www\.)?open\.spotify\.com\/((?P<region>[a-zA-Z-]+)\/)?(user\/(?P<user>[a-zA-Z0-9-_]+)\/)?episode\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'SpotifyShowRegex': re.compile(r'(https?:\/\/)(www\.)?open\.spotify\.com\/((?P<region>[a-zA-Z-]+)\/)?(user\/(?P<user>[a-zA-Z0-9-_]+)\/)?show\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'SpotifyAlbumRegex': re.compile(r'(https?:\/\/)(www\.)?open\.spotify\.com\/((?P<region>[a-zA-Z-]+)\/)?(user\/(?P<user>[a-zA-Z0-9-_]+)\/)?album\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'AllSpotifyRegex': re.compile(r'(https?:\/\/)(www\.)?open\.spotify\.com\/((?P<region>[a-zA-Z-]+)\/)?(user\/(?P<user>[a-zA-Z0-9-_]+)\/)?(?P<type>track|album|playlist|artist|episode|show)\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'AppleMusicRegex': re.compile(r'https?:\/\/?(?:www\.)?music\.apple\.com\/(\S+)'),
    'TidalRegex': re.compile(r'https?:\/\/?(?:www\.)?(?:tidal|listen)\.tidal\.com\/(?P<type>track|album|playlist|artist)\/(?P<identifier>[a-zA-Z0-9-_]+)'),
    'JiosaavnRegex': re.compile(r'(https?:\/\/)(www\.)?jiosaavn\.com\/(?P<type>song|album|featured|artist)\/([a-zA-Z0-9-_/,]+)'),
    'TiktokRegex': re.compile(r'https:\/\/www\.tiktok\.com\/'),
    'MixcloudRegex': re.compile(r'https:\/\/www\.mixcloud\.com\/'),
    'MusicYandexRegex': re.compile(r'https:\/\/music\.yandex\.ru\/'),
    'RadiohostRegex': re.compile(r'https?:\/\/[^.\s]+\.radiohost\.de\/(\S+)')
}


class SearchPlatforms:
    SEARCH_PLATFORMS = SEARCH_PLATFORMS
    LAVALINK_PLUGINS = LAVALINK_PLUGINS
    SOURCE_REGEXES = SOURCE_REGEXES