= Contributors

{page-component-name} allow you to define custom behavior to your addon based on the contributor.

This class is used to define some properties of the wheel.

To add a new contributor you need to :

. Create a new class overriding ContributorABC from {page-component-name}.contributors_api
. Add an entrypoint to your package named "addon_odoo_wheel.contributor"

== Example

NOTE: Can be found in modules/ROOT/partial/sample_contributor

.pyproject.toml
[,toml]
----
include::partial$sample_contributor/pyproject.toml[]
----
<.> Add {page-component-name} as depends
<.> The python entrypoint
<.>  Path to your Class. Here my class is in `\\__init__.py`. `your-name` is not important.

[source,python]
----
include::partial$sample_contributor/src/sample_company_contributor/__init__.py[]
----
<.> Define all the name of your company. Can contain multiple values. The comparaison is case insensitive.
<.> Define the email of your company
<.> Is for your company the Odoo serie is required. If true then all other method will have one.
<.> Allow to override the post strategy based on your git repo.
<.> Allow to define custom classifier for your package. See xref:metadata_classifiers.adoc[]
