= Wheel Name

The name of the wheel can be defined manually or automatically from the addon name.

== Automatic

If no `name` is defined in the section `[project]` of the `pyproject.toml` then the addon name is used as based for the wheel.

The name of the wheel is based on the addon name with a prefix. +
The prefix is defined by the author of the addon found in the `\\__manifest__.py` file. +

The know prefix are:

|===
|Author|Prefix| Depends of the odoo version ?

|Mangono|`mangono-addon`| No
|NDP Systemes|`mangono-addon`| No
|OCA|`odoo-addon`| Yes, see https://github.com/acsone/manifestoo-core/blob/main/src/manifestoo_core/metadata.py#L196[manifestoo-core `pkg_name_pfx` for each version]
|Odoo Community Association (OCA)| `odoo-addon` | Yes, see https://github.com/acsone/manifestoo-core/blob/main/src/manifestoo_core/metadata.py#L196[manifestoo-core `pkg_name_pfx` for each version]
|Other| `addon-odoo` | No
|===

NOTE: The prefix `addon-odoo` is the default arbitrary prefix because `OCA` already use the prefix `odoo-addon`.


== Manual

You can define the wheel name with the field `name` in the section `[project]` of the `pyproject.toml`.

.pyproject.toml
[,toml]
----
[build-system]
requires = ["addon-odoo-wheel"]
build-backend = "addon_odoo_wheel.builder"

[project]
name = "awesome-odoo-addon" # <1>
dynamic = ["version"] # <2>
----
<1> The manual wheel name
<2> Tell to `addon-odoo-wheel` to use the addon version from the `\\__manifest__.py`

=== Security

By default if the `project.name` is not equal to the <<_automatic>> one {page-component-name} failed to build your wheel. +
This to ensure, removing `[project]` and switch to <<_automatic>> will not produce another wheel name.

This can be deactivated with `metadata_src = "manual"` in `[tool.addon-odoo-wheel]`
