from .types import JSONFieldMode as JSONFieldMode, TextFieldMode as TextFieldMode
from _typeshed import Incomplete
from dataclasses import dataclass

logger: Incomplete

@dataclass
class JSONField:
    name: str
    value: dict | str
    mode: JSONFieldMode = ...
    msg: str = ...
    @classmethod
    def form_asserts(cls, k: str, v: dict): ...
    def validate(self, value): ...

@dataclass
class TextField:
    name: str
    value: str | int
    mode: TextFieldMode = ...
    msg: str = ...
    def __post_init__(self) -> None: ...
    @classmethod
    def form_asserts(cls, k, v): ...
    def validate(self, value): ...

def import_func(path): ...
