# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_lead import Riskanalyticsenginev3Lead

class TestRiskanalyticsenginev3Lead(unittest.TestCase):
    """Riskanalyticsenginev3Lead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Riskanalyticsenginev3Lead:
        """Test Riskanalyticsenginev3Lead
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Riskanalyticsenginev3Lead`
        """
        model = Riskanalyticsenginev3Lead()
        if include_optional:
            return Riskanalyticsenginev3Lead(
                count = 56,
                creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                info = [
                    ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_additional_info.riskanalyticsenginev3AdditionalInfo(
                        key = '', 
                        type = 'UNDEFINED_TYPE', 
                        value = '', )
                    ],
                is_observation = True,
                lead_key = '',
                pivot = ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_pivot.riskanalyticsenginev3Pivot(
                    database = '', 
                    database_source_field = 'UNDEFINED', 
                    db_user = '', 
                    id = '', 
                    os_user = '', 
                    server_ip = '', 
                    type = 'UNDEFINED_PIVOT_TYPE', ),
                score = 1.337,
                severity = 56,
                type = 'UNDEFINED_LEAD_TYPE'
            )
        else:
            return Riskanalyticsenginev3Lead(
        )
        """

    def testRiskanalyticsenginev3Lead(self):
        """Test Riskanalyticsenginev3Lead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
