# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.reportsv3_get_chart_query_response import Reportsv3GetChartQueryResponse

class TestReportsv3GetChartQueryResponse(unittest.TestCase):
    """Reportsv3GetChartQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Reportsv3GetChartQueryResponse:
        """Test Reportsv3GetChartQueryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Reportsv3GetChartQueryResponse`
        """
        model = Reportsv3GetChartQueryResponse()
        if include_optional:
            return Reportsv3GetChartQueryResponse(
                chart_layout = ibm_gdsc_sdk_saas.models.reportsv3_chart_display_layout.reportsv3ChartDisplayLayout(
                    chart_headers = [
                        ibm_gdsc_sdk_saas.models.reportsv3_display_header.reportsv3DisplayHeader(
                            aggregation_type = 'UNDEFINED_AGG_TYPE', 
                            field_name = ibm_gdsc_sdk_saas.models.reportsv3_field_name.reportsv3FieldName(
                                customized_value = '', 
                                nls_key = '', 
                                nls_value = '', ), 
                            header_description = ibm_gdsc_sdk_saas.models.reportsv3_header_description.reportsv3HeaderDescription(
                                nls_key = '', 
                                nls_value = '', ), 
                            header_id = '', 
                            header_name = '', 
                            sequence = 56, 
                            table_name = '', )
                        ], 
                    chart_id = '', 
                    report_id = '', 
                    results_limit = 56, ),
                model_type = 'UNDEFINED_MODEL_TYPE',
                query = ''
            )
        else:
            return Reportsv3GetChartQueryResponse(
        )
        """

    def testReportsv3GetChartQueryResponse(self):
        """Test Reportsv3GetChartQueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
