# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.reportsrunnerv3_file_type import Reportsrunnerv3FileType

class TestReportsrunnerv3FileType(unittest.TestCase):
    """Reportsrunnerv3FileType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportsrunnerv3FileType(self):
        """Test Reportsrunnerv3FileType"""
        # inst = Reportsrunnerv3FileType()

if __name__ == '__main__':
    unittest.main()
