# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.api.qs_data_manager_api import QSDataManagerApi


class TestQSDataManagerApi(unittest.TestCase):
    """QSDataManagerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QSDataManagerApi()

    def tearDown(self) -> None:
        pass

    def test_q_s_data_manager_get_master_data(self) -> None:
        """Test case for q_s_data_manager_get_master_data

        Summary: master data for all entities Description: Retrieves All Dimension and Fact tables data.
        """
        pass

    def test_q_s_data_manager_get_plugin_data(self) -> None:
        """Test case for q_s_data_manager_get_plugin_data

        Summary: Plugins Details Description: Retrieves All plugins information.
        """
        pass

    def test_q_s_data_manager_register_scan(self) -> None:
        """Test case for q_s_data_manager_register_scan

        Summary: Insert ScanDetails Description: Register new data into scan dimension table.
        """
        pass

    def test_q_s_data_manager_retrieve_scan(self) -> None:
        """Test case for q_s_data_manager_retrieve_scan

        Summary: Fetch ScanDetails Description: Fetch details from scan dimension table.
        """
        pass


if __name__ == '__main__':
    unittest.main()
