# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.assetsv3_update_asset_name_request import Assetsv3UpdateAssetNameRequest

class TestAssetsv3UpdateAssetNameRequest(unittest.TestCase):
    """Assetsv3UpdateAssetNameRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Assetsv3UpdateAssetNameRequest:
        """Test Assetsv3UpdateAssetNameRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Assetsv3UpdateAssetNameRequest`
        """
        model = Assetsv3UpdateAssetNameRequest()
        if include_optional:
            return Assetsv3UpdateAssetNameRequest(
                grouper_id = 56,
                updated_name = ''
            )
        else:
            return Assetsv3UpdateAssetNameRequest(
        )
        """

    def testAssetsv3UpdateAssetNameRequest(self):
        """Test Assetsv3UpdateAssetNameRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
