# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_generate_leads_response import Riskanalyticsenginev3GenerateLeadsResponse

class TestRiskanalyticsenginev3GenerateLeadsResponse(unittest.TestCase):
    """Riskanalyticsenginev3GenerateLeadsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Riskanalyticsenginev3GenerateLeadsResponse:
        """Test Riskanalyticsenginev3GenerateLeadsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Riskanalyticsenginev3GenerateLeadsResponse`
        """
        model = Riskanalyticsenginev3GenerateLeadsResponse()
        if include_optional:
            return Riskanalyticsenginev3GenerateLeadsResponse(
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pivot_type = 'UNDEFINED_PIVOT_TYPE',
                risks = [
                    ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_risk.riskanalyticsenginev3Risk(
                        classification_details = ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_classification_details.riskanalyticsenginev3ClassificationDetails(
                            class_description_nls = '', 
                            class_key = '', 
                            class_nls = '', 
                            class_observations = [
                                ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_classification_observation.riskanalyticsenginev3ClassificationObservation(
                                    is_supporting_observation = True, 
                                    key = '', 
                                    original_value = 1.337, )
                                ], 
                            class_value = 1.337, 
                            classification_match_details = [
                                ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_classification_match_details.riskanalyticsenginev3ClassificationMatchDetails(
                                    class_key = '', 
                                    class_value = 1.337, 
                                    classification_confidence = 1.337, 
                                    classification_nls = '', 
                                    model_probability = 1.337, )
                                ], 
                            classification_modified = True, ), 
                        creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        feature_sets = [
                            ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_feature_set.riskanalyticsenginev3FeatureSet(
                                features = [
                                    ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_feature.riskanalyticsenginev3Feature(
                                        feature_nls = '', 
                                        is_observation = True, 
                                        is_zero = True, 
                                        key = '', 
                                        method_type = 'UNDEFINED_METHOD_TYPE', 
                                        original_value = 1.337, 
                                        score = 56, 
                                        sequence = 56, 
                                        severity_level = 'UNDEFINED_SEVERITY_LEVEL', 
                                        value = 1.337, )
                                    ], 
                                name = '', )
                            ], 
                        id = '', 
                        is_emerging = True, 
                        leads = [
                            ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_lead.riskanalyticsenginev3Lead(
                                count = 56, 
                                creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                info = [
                                    ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_additional_info.riskanalyticsenginev3AdditionalInfo(
                                        key = '', 
                                        type = 'UNDEFINED_TYPE', 
                                        value = '', )
                                    ], 
                                is_observation = True, 
                                lead_key = '', 
                                pivot = ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_pivot.riskanalyticsenginev3Pivot(
                                    database = '', 
                                    database_source_field = 'UNDEFINED', 
                                    db_user = '', 
                                    id = '', 
                                    os_user = '', 
                                    server_ip = '', ), 
                                score = 1.337, 
                                severity = 56, 
                                type = 'UNDEFINED_LEAD_TYPE', )
                            ], 
                        pivot = ibm_gdsc_sdk_saas.models.riskanalyticsenginev3_pivot.riskanalyticsenginev3Pivot(
                            database = '', 
                            db_user = '', 
                            id = '', 
                            os_user = '', 
                            server_ip = '', ), 
                        score = 56, 
                        severity_level = 'UNDEFINED_SEVERITY_LEVEL', 
                        start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Riskanalyticsenginev3GenerateLeadsResponse(
        )
        """

    def testRiskanalyticsenginev3GenerateLeadsResponse(self):
        """Test Riskanalyticsenginev3GenerateLeadsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
