# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.guardiumconnectorv3_gdp_report_parameter import Guardiumconnectorv3GDPReportParameter

class TestGuardiumconnectorv3GDPReportParameter(unittest.TestCase):
    """Guardiumconnectorv3GDPReportParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Guardiumconnectorv3GDPReportParameter:
        """Test Guardiumconnectorv3GDPReportParameter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Guardiumconnectorv3GDPReportParameter`
        """
        model = Guardiumconnectorv3GDPReportParameter()
        if include_optional:
            return Guardiumconnectorv3GDPReportParameter(
                parameter_value = '',
                paremeter_name = ''
            )
        else:
            return Guardiumconnectorv3GDPReportParameter(
        )
        """

    def testGuardiumconnectorv3GDPReportParameter(self):
        """Test Guardiumconnectorv3GDPReportParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
