# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.workflowv3_job_count import Workflowv3JobCount

class TestWorkflowv3JobCount(unittest.TestCase):
    """Workflowv3JobCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Workflowv3JobCount:
        """Test Workflowv3JobCount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Workflowv3JobCount`
        """
        model = Workflowv3JobCount()
        if include_optional:
            return Workflowv3JobCount(
                name = '',
                scheduled_job_id = '',
                total = 56
            )
        else:
            return Workflowv3JobCount(
        )
        """

    def testWorkflowv3JobCount(self):
        """Test Workflowv3JobCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
