# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.reportsv3_get_grades_response import Reportsv3GetGradesResponse

class TestReportsv3GetGradesResponse(unittest.TestCase):
    """Reportsv3GetGradesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Reportsv3GetGradesResponse:
        """Test Reportsv3GetGradesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Reportsv3GetGradesResponse`
        """
        model = Reportsv3GetGradesResponse()
        if include_optional:
            return Reportsv3GetGradesResponse(
                grades_list = [
                    ibm_gdsc_sdk_saas.models.reportsv3_grade.reportsv3Grade(
                        control_id = 56, 
                        create_user_id = '', 
                        create_user_name = '', 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        default_score = 56, 
                        default_score_name = '', 
                        description = '', 
                        grade_id = 56, 
                        grade_threshold = [
                            ibm_gdsc_sdk_saas.models.reportsv3_grade_threshold.reportsv3GradeThreshold(
                                threshold_score = 56, 
                                threshold_score_name = '', 
                                threshold_value = 1.337, )
                            ], 
                        is_percentage = True, 
                        metric_id = 56, 
                        name = '', 
                        recommendation = '', 
                        update_user_id = '', 
                        update_user_name = '', )
                    ]
            )
        else:
            return Reportsv3GetGradesResponse(
        )
        """

    def testReportsv3GetGradesResponse(self):
        """Test Reportsv3GetGradesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
