# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.reportsv3_artifact import Reportsv3Artifact

class TestReportsv3Artifact(unittest.TestCase):
    """Reportsv3Artifact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Reportsv3Artifact:
        """Test Reportsv3Artifact
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Reportsv3Artifact`
        """
        model = Reportsv3Artifact()
        if include_optional:
            return Reportsv3Artifact(
                artifact_id = '',
                create_user_id = '',
                create_user_name = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                type = 'ARTIFACT_UNKNOWN',
                update_user_id = '',
                update_user_name = ''
            )
        else:
            return Reportsv3Artifact(
        )
        """

    def testReportsv3Artifact(self):
        """Test Reportsv3Artifact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
