# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.vulnerabilities_summary import VulnerabilitiesSummary

class TestVulnerabilitiesSummary(unittest.TestCase):
    """VulnerabilitiesSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VulnerabilitiesSummary:
        """Test VulnerabilitiesSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VulnerabilitiesSummary`
        """
        model = VulnerabilitiesSummary()
        if include_optional:
            return VulnerabilitiesSummary(
                criticality_count = [
                    ibm_gdsc_sdk_saas.models.vulnerabilities_criticality_count_inner.VulnerabilitiesCriticalityCount_inner(
                        criticality = 'HIGH', 
                        count = 5, )
                    ],
                vulnerability_type_count = [
                    ibm_gdsc_sdk_saas.models.vulnerabilities_summary_vulnerability_type_count_inner.VulnerabilitiesSummary_vulnerabilityTypeCount_inner(
                        vulnerability_type = 'public-facing', 
                        count = 10, )
                    ],
                status_type_count = [
                    ibm_gdsc_sdk_saas.models.vulnerabilities_summary_status_type_count_inner.VulnerabilitiesSummary_statusTypeCount_inner(
                        status_type = 'review', 
                        count = 1, )
                    ],
                status_summary = ibm_gdsc_sdk_saas.models.vulnerabilities_summary_status_summary.VulnerabilitiesSummary_statusSummary(
                    recently_discovered = 12, 
                    open = 34, 
                    fixed = 56, ),
                affected_data_store_summary = ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary.VulnerabilitiesSummary_affectedDataStoreSummary(
                    cloud_account_ids_count = [
                        ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary_cloud_account_ids_count_inner.VulnerabilitiesSummary_affectedDataStoreSummary_cloudAccountIdsCount_inner(
                            cloud_account_id = '123456789101', 
                            count = 1, )
                        ], 
                    cloud_regions_count = [
                        ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary_cloud_regions_count_inner.VulnerabilitiesSummary_affectedDataStoreSummary_cloudRegionsCount_inner(
                            cloud_region = '', 
                            count = 1.337, )
                        ], 
                    data_store_types = [
                        ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary_data_store_types_inner.VulnerabilitiesSummary_affectedDataStoreSummary_dataStoreTypes_inner(
                            data_store_type = '', 
                            count = 1.337, )
                        ], )
            )
        else:
            return VulnerabilitiesSummary(
                criticality_count = [
                    ibm_gdsc_sdk_saas.models.vulnerabilities_criticality_count_inner.VulnerabilitiesCriticalityCount_inner(
                        criticality = 'HIGH', 
                        count = 5, )
                    ],
                vulnerability_type_count = [
                    ibm_gdsc_sdk_saas.models.vulnerabilities_summary_vulnerability_type_count_inner.VulnerabilitiesSummary_vulnerabilityTypeCount_inner(
                        vulnerability_type = 'public-facing', 
                        count = 10, )
                    ],
                status_type_count = [
                    ibm_gdsc_sdk_saas.models.vulnerabilities_summary_status_type_count_inner.VulnerabilitiesSummary_statusTypeCount_inner(
                        status_type = 'review', 
                        count = 1, )
                    ],
                status_summary = ibm_gdsc_sdk_saas.models.vulnerabilities_summary_status_summary.VulnerabilitiesSummary_statusSummary(
                    recently_discovered = 12, 
                    open = 34, 
                    fixed = 56, ),
                affected_data_store_summary = ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary.VulnerabilitiesSummary_affectedDataStoreSummary(
                    cloud_account_ids_count = [
                        ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary_cloud_account_ids_count_inner.VulnerabilitiesSummary_affectedDataStoreSummary_cloudAccountIdsCount_inner(
                            cloud_account_id = '123456789101', 
                            count = 1, )
                        ], 
                    cloud_regions_count = [
                        ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary_cloud_regions_count_inner.VulnerabilitiesSummary_affectedDataStoreSummary_cloudRegionsCount_inner(
                            cloud_region = '', 
                            count = 1.337, )
                        ], 
                    data_store_types = [
                        ibm_gdsc_sdk_saas.models.vulnerabilities_summary_affected_data_store_summary_data_store_types_inner.VulnerabilitiesSummary_affectedDataStoreSummary_dataStoreTypes_inner(
                            data_store_type = '', 
                            count = 1.337, )
                        ], ),
        )
        """

    def testVulnerabilitiesSummary(self):
        """Test VulnerabilitiesSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
