"""
Core Constants for MSA Reasoning Kernel
=======================================

Centralized constants to improve maintainability and eliminate magic numbers.
All timeout values, limits, and configuration defaults are defined here.
"""

# Execution timeouts (in seconds)
EXECUTION_TIMEOUT = 30
MAX_EXECUTION_TIMEOUT = 1800  # 30 minutes
MIN_EXECUTION_TIMEOUT = 10
DEFAULT_REASONING_TIMEOUT = 300  # 5 minutes
DAYTONA_SANDBOX_TIMEOUT = 30
REDIS_OPERATION_TIMEOUT = 5

# Retry configuration
MAX_RETRY_ATTEMPTS = 3
RETRY_BASE_DELAY = 1.0  # seconds
RETRY_MAX_DELAY = 60.0  # seconds
RETRY_BACKOFF_MULTIPLIER = 2.0

# Cache configuration
DEFAULT_CACHE_TTL = 3600  # 1 hour in seconds
MAX_CACHE_TTL = 86400  # 24 hours
SHORT_CACHE_TTL = 300  # 5 minutes
REASONING_RESULT_TTL = 7200  # 2 hours

# Input validation limits
MAX_SCENARIO_LENGTH = 10000
MIN_SCENARIO_LENGTH = 10
MAX_CONTEXT_DEPTH = 5
MAX_ARRAY_LENGTH = 100
MAX_STRING_LENGTH = 5000
MAX_SESSION_ID_LENGTH = 100
MAX_CONTEXT_KEYS = 50
MAX_CONTEXT_KEY_LENGTH = 100

# Request limits
MAX_REQUEST_SIZE_MB = 10.0
MAX_JSON_DEPTH = 10
MAX_QUERY_PARAMS = 50
MAX_PATH_PARAMS = 10
MAX_HEADER_SIZE = 8192
MAX_CONCURRENT_REQUESTS_PER_KEY = 10

# Probabilistic inference defaults
DEFAULT_INFERENCE_SAMPLES = 1000
MIN_INFERENCE_SAMPLES = 100
MAX_INFERENCE_SAMPLES = 5000
DEFAULT_INFERENCE_CHAINS = 4
MIN_INFERENCE_CHAINS = 1
MAX_INFERENCE_CHAINS = 8

# Circuit breaker configuration
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_RECOVERY_TIMEOUT = 60  # seconds
CIRCUIT_BREAKER_SUCCESS_THRESHOLD = 3
CIRCUIT_BREAKER_TIMEOUT = 30

# Rate limiting
RATE_LIMIT_WINDOW = 3600  # 1 hour in seconds
DEFAULT_RATE_LIMIT_PER_HOUR = 1000
HIGH_PRIORITY_RATE_LIMIT = 5000
ADMIN_RATE_LIMIT = 10000

# Daytona sandbox configuration
DAYTONA_DEFAULT_CPU_LIMIT = 2
DAYTONA_DEFAULT_MEMORY_MB = 512
DAYTONA_DEFAULT_STORAGE_MB = 50
DAYTONA_MAX_CPU_LIMIT = 4
DAYTONA_MAX_MEMORY_MB = 2048
DAYTONA_MAX_STORAGE_MB = 500

# Security configuration
API_KEY_LENGTH = 32
API_KEY_PREFIX_LENGTH = 8
MAX_API_KEYS_PER_USER = 10
API_KEY_DEFAULT_EXPIRY_DAYS = 365
PASSWORD_MIN_LENGTH = 12
BCRYPT_ROUNDS = 12

# MSA Pipeline stages
MSA_STAGE_COUNT = 5
MSA_STAGE_TIMEOUT = 120  # 2 minutes per stage
MSA_MAX_PARALLEL_STAGES = 2

# WebSocket configuration
WEBSOCKET_PING_INTERVAL = 30  # seconds
WEBSOCKET_PONG_TIMEOUT = 10  # seconds
WEBSOCKET_MAX_MESSAGE_SIZE = 1048576  # 1MB

# Redis configuration
REDIS_DEFAULT_PORT = 6379
REDIS_CONNECTION_POOL_SIZE = 10
REDIS_MAX_CONNECTIONS = 50
REDIS_HEALTH_CHECK_INTERVAL = 30
REDIS_RECONNECT_ATTEMPTS = 3

# Monitoring and observability
HEALTH_CHECK_TIMEOUT = 5
METRICS_COLLECTION_INTERVAL = 60
LOG_RETENTION_DAYS = 30
AUDIT_LOG_RETENTION_DAYS = 90

# World model configuration
WORLD_MODEL_MAX_SIZE_MB = 100
WORLD_MODEL_CACHE_SIZE = 1000
WORLD_MODEL_UPDATE_BATCH_SIZE = 50

# File and directory limits
MAX_FILE_SIZE_MB = 50
MAX_DIRECTORY_DEPTH = 10
MAX_FILES_PER_DIRECTORY = 1000

# API versioning
API_VERSION_V1 = "v1"
API_VERSION_V2 = "v2"
API_CURRENT_VERSION = API_VERSION_V2

# Environment types
ENV_DEVELOPMENT = "development"
ENV_STAGING = "staging"
ENV_PRODUCTION = "production"
ENV_TESTING = "testing"

# Priority levels
PRIORITY_LOW = "low"
PRIORITY_NORMAL = "normal"
PRIORITY_HIGH = "high"

# Reasoning modes
MODE_KNOWLEDGE = "knowledge"
MODE_PROBABILISTIC = "probabilistic"
MODE_BOTH = "both"

# Status codes
STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
STATUS_SUSPENDED = "suspended"
STATUS_PENDING = "pending"
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"

# Validation patterns
PATTERN_SESSION_ID = r"^[a-zA-Z0-9_-]+$"
PATTERN_API_KEY = r"^[a-zA-Z0-9_-]+$"
PATTERN_UUID = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
PATTERN_EMAIL = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"

# Error codes
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
ERROR_AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
ERROR_RATE_LIMITED = "RATE_LIMITED"
ERROR_INTERNAL_SERVER = "INTERNAL_SERVER_ERROR"
ERROR_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
ERROR_TIMEOUT = "TIMEOUT"
ERROR_INVALID_REQUEST = "INVALID_REQUEST"

# HTTP status codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_NO_CONTENT = 204
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_TOO_MANY_REQUESTS = 429
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_SERVICE_UNAVAILABLE = 503
