# Generated by Django 5.2 on 2025-05-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectedissues', '0005_initial'),
        ('medicationdispenses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationdispense',
            name='not_performed_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medication_dispense_not_performed_reason', to='detectedissues.detectedissuecodeablereference'),
        ),
    ]
