# Stub for optional Rust extension to satisfy type-checking
# Copyright (C) 2024 quip.network
# SPDX-License-Identifier: AGPL-3.0-or-later

class WotsPlusKeccak256:
    def __init__(self) -> None: ...
    @staticmethod
    def hash_len() -> int: ...
    @staticmethod
    def message_len() -> int: ...
    @staticmethod
    def chain_len() -> int: ...
    @staticmethod
    def signature_size() -> int: ...
    def generate_key_pair(self, private_seed: bytes) -> tuple[bytes, bytes]: ...
    def get_public_key(self, private_key: bytes) -> bytes: ...
    def sign(self, private_key: bytes, message: bytes) -> bytes: ...
    def verify(self, public_key: bytes, message: bytes, signature: bytes) -> bool: ...

