
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-28T09:45:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "43a2c9ea8e04693de24cb0535a8bd7ffa5a2f927",
 "version": "1.3.10-rc.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
