# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is Similarity Search Engine for executable binaries

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.app_api_rest_v1_analyse_schema_status import AppApiRestV1AnalyseSchemaStatus

class TestAppApiRestV1AnalyseSchemaStatus(unittest.TestCase):
    """AppApiRestV1AnalyseSchemaStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppApiRestV1AnalyseSchemaStatus(self):
        """Test AppApiRestV1AnalyseSchemaStatus"""
        # inst = AppApiRestV1AnalyseSchemaStatus()

if __name__ == '__main__':
    unittest.main()
