# -*- coding: utf-8 -*-

"""
openaiapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Metadata2(object):

    """Implementation of the 'Metadata2' model.

    Attributes:
        user_id (str): The model property of type str.
        custom_field (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_id": 'user_id',
        "custom_field": 'custom_field'
    }

    def __init__(self,
                 user_id=None,
                 custom_field=None):
        """Constructor for the Metadata2 class"""

        # Initialize members of the class
        self.user_id = user_id 
        self.custom_field = custom_field 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        user_id = dictionary.get("user_id") if dictionary.get("user_id") else None
        custom_field = dictionary.get("custom_field") if dictionary.get("custom_field") else None
        # Return an object of this model
        return cls(user_id,
                   custom_field)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'user_id={self.user_id!r}, '
                f'custom_field={self.custom_field!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'user_id={self.user_id!s}, '
                f'custom_field={self.custom_field!s})')
