# -*- coding: utf-8 -*-

"""
openaiapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from openaiapi.api_helper import APIHelper
from openaiapi.models.hyperparameters_2 import Hyperparameters2


class Supervised1(object):

    """Implementation of the 'Supervised1' model.

    Attributes:
        hyperparameters (Hyperparameters2): The model property of type
            Hyperparameters2.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "hyperparameters": 'hyperparameters'
    }

    def __init__(self,
                 hyperparameters=None):
        """Constructor for the Supervised1 class"""

        # Initialize members of the class
        self.hyperparameters = hyperparameters 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        hyperparameters = Hyperparameters2.from_dictionary(dictionary.get('hyperparameters')) if dictionary.get('hyperparameters') else None
        # Return an object of this model
        return cls(hyperparameters)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(value=dictionary.hyperparameters,
                                           type_callable=lambda value: Hyperparameters2.validate(value),
                                           is_model_dict=True)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(value=dictionary.get('hyperparameters'),
                                       type_callable=lambda value: Hyperparameters2.validate(value),
                                       is_model_dict=True)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'hyperparameters={self.hyperparameters!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'hyperparameters={self.hyperparameters!s})')
