# Generated by Django 5.2 on 2025-04-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverseevents', '0003_initial'),
        ('base', '0003_initial'),
        ('familymemberhistories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseeventcontributingfactorreference',
            name='family_member_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contributing_factor_reference_family_member_history', to='familymemberhistories.familymemberhistory'),
        ),
        migrations.AddField(
            model_name='adverseeventcontributingfactorreference',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contributing_factor_reference_identifier', to='base.identifier'),
        ),
    ]
