# Generated by Django 5.2 on 2025-04-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverseevents', '0006_initial'),
        ('medicationstatements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseeventcontributingfactorreference',
            name='medication_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contributing_factor_reference_medication_statement', to='medicationstatements.medicationstatement'),
        ),
    ]
