= Http Configuration

The converter `ConfigConverterHttp` allow to convert environment variable related to http configuration to valid odoo CLI.

include::partial$http.adoc[]


== http_enable
Disable the http and longpolling services entirely

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `HTTP_ENABLE` is used and expect a `bool`.

Possible cli:

* --no-http

== http_interface
Listen interface address for http services. keep empty to listen on all interfaces (0.0.0.0)

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `HTTP_INTERFACE` is used and expect a `str`.

Possible cli:

* --http-interface

== http_port
Listen port for the main http service. keep empty to listen on all interfaces (0.0.0.0)

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `HTTP_PORT` is used and expect a `int`.

Possible cli:

* --http-port

== gevent_port
Listen port for the gevent (longpolling) worker.for prior version see longpolling_port

TIP: Supported Odoo version from 16.0 until 18.0

The environment variable `GEVENT_PORT` is used and expect a `int`.

Possible cli:

* --gevent-port

== longpolling_port
Listen port for the gevent (longpolling) worker.

TIP: Supported Odoo version from 11.0 until 15.0

The environment variable `GEVENT_PORT` is used and expect a `Any`.

Possible cli:

* --longpolling-port

== proxy_mode
Activate reverse proxy wsgi wrappers (headers rewriting).
        only enable this when running behind a trusted web proxy!

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `PROXY_MODE` is used and expect a `bool`.

Possible cli:

* --proxy-mode

== x_sendfile
Activate x-sendfile (apache) and x-accel-redirect (nginx)
        http response header to delegate the delivery of large
        files (assets/attachments) to the web server.

TIP: Supported Odoo version from 16.0 until 18.0

The environment variable `X_SENDFILE` is used and expect a `bool`.

Possible cli:

* --x-sendfile



== Other keys


=== HTTP_ENABLE
NOTE: Convert environ key=http_enable to <object object at 0x78756c55d420>

The environment variable `HTTP_ENABLE` is used and expect a `bool`.
