= Logging Configuration

The converter `ConfigConverterLogging` allow to convert environment variable related to logging configuration to valid odoo CLI.

include::partial$log.adoc[]


== logfile
File where the server log will be stored

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LOGFILE` is used and expect a `Path`.

Possible cli:

* --logfile

== syslog
Send the log to the syslog server

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `USE_SYSLOG` is used and expect a `bool`.

Possible cli:

* --syslog

== log_handler
NOTE: Setup a handler at level for a given prefix. an empty prefix indicates the root logger.
        this option can be repeated. example: "odoo.orm:debug" or "werkzeug:critical" (default: ":info") with `Possible cli:

* --log-handler`

The environment variable `LOG_HANDLER` is repeatable.
This mean a suffix can be added after an **single** `_`. For example `LOG_HANDLER_value`, the suffix is `value` not `_value`

The behavior depends of the value.

* If the value is "True" then the suffix is used.
* If the value is "False" then value is discard
* If the value is not a boolean (int, float, string, csv) then the suffix is taken has value.

[,shell]
----
LOG_HANDLER="v1,v2" # <.>
LOG_HANDLER_0="v0,bar" # <.>
LOG_HANDLER_1="1" # <.>
LOG_HANDLER_FOO="True" # <.>
LOG_HANDLER_XX="bar" # <.>
----
<.> Classic csv value
<.> csv value : don't use the suffix
<.> Not a boolean value : use the value
<.> Boolean value: The suffix `FOO` is used
<.> Not a boolean value : use the value

The result (the order is not constant) will be ["v1", "v2", "v0", "foo", "bar"].

NOTE: Like csv value, all the value are deduplicated


== log_db
Logging database

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LOG_DB` is used and expect a `bool`.

Possible cli:

* --log-db

== log_db_level
Logging database level

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LOG_DB_LEVEL` is used and expect a `str`.

Possible cli:

* --log-db-level

== log_level
Specify the level of the logging. accepted values: ['info', 'debug_rpc', 'warn', 'test', 'critical', 'runbot', 'debug_sql', 'error', 'debug', 'debug_rpc_answer', 'notset'].

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LOG_LEVEL` is used and expect a `str`.

Possible cli:

* --log-level



== Other keys


=== LOG_WEB
NOTE: Shortcut for --log-handler=odoo.http:debug

The environment variable `LOG_WEB` is used and expect a `bool`.

=== LOG_SQL
NOTE: Enable web logging

The environment variable `LOG_SQL` is used and expect a `bool`.

=== LOG_REQUEST
NOTE: Shortcut for --log-handler=odoo.http.rpc.request:debug

The environment variable `LOG_REQUEST` is used and expect a `bool`.

=== LOG_RESPONSE
NOTE: Shortcut for --log-handler=odoo.http.rpc.response:debug

The environment variable `LOG_RESPONSE` is used and expect a `bool`.
