SELECT BOOKMARK_END_DATE + INTERVAL '1 day' as BOOKMARK_START_DATE
        , TO_DATE(CONVERT_TIMEZONE('UTC',     current_timestamp() - INTERVAL '1 day'))  as BOOKMARK_END_DATE
FROM <DATABASE_NAME>.<SCHEMA>.pybrv_metadata
WHERE UNIQUE_RULE_IDENTIFIER = '<UNIQUE_RULE_IDENTIFIER>'
