"""
Type stubs for pyxpcsviewer XPCS data handling library.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import numpy as np

class DataExtractor:
    def __init__(self, file_path: Union[str, Path]) -> None: ...
    def get_correlation_data(self) -> Dict[str, Any]: ...
    def get_experimental_data(self) -> Dict[str, Any]: ...
    def get_metadata(self) -> Dict[str, Any]: ...

def load_xpcs_data(file_path: Union[str, Path]) -> Dict[str, Any]: ...
def extract_correlation_function(
    data: Dict[str, Any], angle_filter: Optional[List[float]] = ...
) -> np.ndarray: ...
