DIURETICS_TERMS = [
    "furosemide",
    "lasix",
    "bumetanide",
    "bumex",
    "torsemide",
    "demadex",
    "ethacrynic acid",
    "edecrin",
    "metolazone",
    "zaroxolyn",
    "spironolactone",
    "aldactone",
    "hydrochlorothiazide",
    "microzide",
    "amiloride",
    "midamor",
    "triamterene",
    "dyrenium",
    "eplerenone",
    "inspra",
]
