GLP1_MEDS_TERMS = [
    "lixisenatide",
    "adlyxin",
    "albiglutide",
    "tanzeum",
    "exenatide",
    "bydureon bcise",
    "bydureon",
    "byetta",
    "liraglutide",
    "saxenda",
    "victoza",
    "dulaglutide",
    "trulicity",
    "semaglutide",
    "ozempic",
    "rybelsus",
    "tirzepatide",
    "mounjaro",
    "zepbound",
]
