from .constants import SOURCE_KEY_RESERVED_V2 as SOURCE_KEY_RESERVED_V2
from .internal_utils.fallback_logger import sdk_logger as sdk_logger
from _typeshed import Incomplete
from typing import TextIO

class StdoutWriter:
    original_stdout: Incomplete
    def __init__(self, original_stdout: TextIO) -> None: ...
    def write(self, text: str) -> int: ...
    def flush(self) -> None: ...
    def isatty(self) -> bool: ...
    def fileno(self) -> int: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def __getattr__(self, name: str): ...

class StdoutOverride:
    @classmethod
    def enable(cls) -> None: ...
    @classmethod
    def disable(cls) -> None: ...
    @classmethod
    def is_enabled(cls) -> bool: ...

def enable_stdout_override() -> None: ...
def disable_stdout_override() -> None: ...
def is_stdout_override_enabled() -> bool: ...
