from .internal_utils.fallback_logger import sdk_logger as sdk_logger
from typing import Any

class ExceptionHandlers:
    @classmethod
    def register(cls) -> None: ...
    @classmethod
    def unregister(cls) -> None: ...
    @classmethod
    def get_original_excepthook(cls) -> Any | None: ...
    @classmethod
    def get_original_threading_excepthook(cls) -> Any | None: ...
    @classmethod
    def get_original_loop_exception_handler(cls) -> Any | None: ...
