from .batch import ObjectBatch as ObjectBatch
from .config import LumberjackConfig as LumberjackConfig
from .internal_utils.fallback_logger import sdk_logger as sdk_logger
from .object_exporter import ObjectExporter as ObjectExporter
from typing import Any

class ObjectRegistration:
    def __init__(self, config: LumberjackConfig) -> None: ...
    def register_object(self, obj: Any = None, **kwargs: Any) -> None: ...
    def flush_objects(self) -> int: ...
    def get_object_batch(self) -> ObjectBatch: ...
    def update_config(self, config: LumberjackConfig) -> None: ...
    def update_exporter(self, exporter: ObjectExporter | None) -> None: ...
    def shutdown(self) -> None: ...
