from opentelemetry import context, trace
from opentelemetry.trace import SpanContext

def extract_trace_context(headers: dict[str, str] | str, carrier_key: str = 'traceparent') -> context.Context | None: ...
def get_span_context_from_headers(headers: dict[str, str] | str, carrier_key: str = 'traceparent') -> SpanContext | None: ...
def start_span_with_remote_parent(span_name: str, headers: dict[str, str] | str, tracer: trace.Tracer | None = None, carrier_key: str = 'traceparent') -> trace.Span: ...
def inject_trace_context(context_to_inject: context.Context | None = None, carrier: dict[str, str] | None = None) -> dict[str, str]: ...
def parse_traceparent(traceparent: str) -> dict[str, str] | None: ...
def establish_trace_context(trace_id: str, parent_span_id: str, clear_existing: bool = True) -> SpanContext: ...
