from http import HTTPStatus
#通过默认值来设置环境变量
KTOOL_LOGGING_LEVEL_ENV = "KTOOL_LOGGING_LEVEL"

KTOOL_DEBUG_ENV = "KTOOL_DEBUG"

#KTOOL_API_SERVER = "10.10.206.126:8091"
KTOOL_API_VERSION_ENV = "KTOOL_API_VERSION"
KTOOL_API_KEY_ENV = "KTOOL_API_KEY"
KTOOL_API_SERVER_ENV = "KTOOL_API_SERVER"

REPEATABLE_STATUS = [
    HTTPStatus.SERVICE_UNAVAILABLE, HTTPStatus.GATEWAY_TIMEOUT
]

SSE_CONTENT_TYPE = 'text/event-stream'

KTOOL_AGENT_LIST = [
    '渗透测试专家'
]

class TaskStatus:
    PENDING = 'PENDING'
    SUSPENDED = 'SUSPENDED'
    SUCCEEDED = 'SUCCEEDED'
    CANCELED = 'CANCELED'
    RUNNING = 'RUNNING'
    FAILED = 'FAILED'
    UNKNOWN = 'UNKNOWN'

class KToolAPICode:
    SUCCESS = 0
    FAILURE = -1