{
    'name': 'Odoo Instance',
    'version': '16.0.2.0.0',
    'category': 'Project',
    'summary': 'Manage Odoo instances with relevant information',
    'author': 'Coopdevs',
    'website': 'https://www.coopdevs.org',
    'depends': ['base', 'contract', 'project', 'calendar', 'queue_job'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'views/odoo_instance_view.xml',
        'views/odoo_module_view.xml',
        'views/odoo_instance_window_wizard_view.xml',
        'views/odoo_version_view.xml',
        'views/odoo_process_view.xml',
        'views/odoo_release_view.xml',
        'views/res_partner_view.xml',
        'views/project_project_view.xml',
        'views/odoo_instance_module_version_views.xml',
        'views/odoo_instance_actions.xml',
        'views/odoo_instance_menuitems.xml',
        'views/odoo_instance_searches.xml',
        'data/ir_cron.xml',
        'data/calendar_tags.xml',
        'data/odoo_version_data.xml',
        'data/odoo14_core_modules_app_data.xml',
        'data/odoo12_core_modules_data.xml',
    ],
    'external_dependencies': {
        'python': ['pyyaml'],
    },
    'images': ['static/src/img/icon.png'],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'AGPL-3',
}
