# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-07-16 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0002_auto_20210112_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='\u81ea\u7531\u6253\u5361'),
        ),
    ]
