{
 "title": "Cascade Agent Network State",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Agent knowledge tree ",
   "type": "nodeGraph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "network_status_offline", "legendFormat": "{{id}}" },
    { "expr": "network_status_links", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Agent Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_status_uptime", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Agent RTT to pub/sub broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "network_status_rtt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prompts received",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "network_status_in_messages", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Prompts sent (cascaded + returned)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "network_status_out_messages", "legendFormat": "{{name}}" }
   ]
  }
 ]
}