= Database Configuration

The converter `ConfigConverterDatabase` allow to convert environment variable related to database configuration to valid odoo CLI.

include::partial$database.adoc[]


== db_name
Specify the database name

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_NAME` is used and expect a `str`.

Possible cli:

* -d
* --database

== db_host
Specify the database host

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_HOST` is used and expect a `str`.

Possible cli:

* --db_host

== db_port
Specify the database port

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_PORT` is used and expect a `int`.

Possible cli:

* --db_port

== db_user
Specify the database user name

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_USER` is used and expect a `str`.

Possible cli:

* -r
* --db_user

== db_password
Specify the database password

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_PASSWORD` is used and expect a `str`.

Possible cli:

* -w
* --db_password

== maxconn_gevent
Specify the maximum number of physical connections to postgresql by the gevent process

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_MAXCONN_GEVENT` is used and expect a `int`.

Possible cli:

* --db_maxconn_gevent

== db_maxconn
Specify the maximum number of physical connections to postgresql

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_MAX_CONN` is used and expect a `int`.

Possible cli:

* --db_maxconn

== db_replica_host
Specify the replica host. specify an empty db_replica_host to use the default unix socket.

TIP: Only Odoo version 18.0 is supported

The environment variable `DB_REPLICA_HOST` is used and expect a `str`.

Possible cli:

* --db_replica_host

== db_replica_port
Specify the replica port

TIP: Only Odoo version 18.0 is supported

The environment variable `DB_REPLICA_PORT` is used and expect a `int`.

Possible cli:

* --db_replica_port

== db_template
Specify a custom database template to create a new database

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_TEMPLATE` is used and expect a `str`.

Possible cli:

* --db_template

== sslmode
NOTE: Specify the database ssl connection mode (see postgresql documentation) with `Possible cli:

* --db_sslmode`

The environment variable `DB_SSL_MODE` is used and expect a `str`.
Possible cli:

* --db_sslmode
Possible value are:

* disable
* allow
* prefer
* require
* verify-ca
* verify-full

== list_db
Disable the ability to obtain or view the list of databases.
        also disable access to the database manager and selector,
        so be sure to set a proper --database parameter first

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIST_DB` is used and expect a `bool`.

Possible cli:

* --no-database-list

== dbfilter
Regular expressions for filtering available databases for web ui.
        the expression can use %d (domain) and %h (host) placeholders.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `DB_FILTER` is used and expect a `str`.

Possible cli:

* --db-filter



== Other keys


=== DB_MAX_CONN_MODE
NOTE: Convert environ key=db_max_conn_mode to <object object at 0x78756c55d420>

The environment variable `DB_MAX_CONN_MODE` is used and expect a `MaxConnMode`.

=== <object object at 0x78756c55d530>
NOTE: Specify the pg executable path

The environment variable `<object object at 0x78756c55d530>` is used and expect a `FFFFFFFFFFFFF`.
