= Worker or Threaded server POSIX Limit Configuration

The converter `ConfigConverterLimit` allow to convert environment variable related to worker or threaded server posix limit configuration to valid odoo CLI.

include::partial$process_limit.adoc[]


== limit_request
Maximum number of request to be processed per worker (default 65536).

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIMIT_REQUEST` is used and expect a `int`.

Possible cli:

* --limit-request

== limit_time_cpu
Maximum allowed cpu time per request (default 60).

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIMIT_TIME_CPU` is used and expect a `int`.

Possible cli:

* --limit-time-cpu

== limit_time_real
Maximum allowed real time per request in seconds (default 120).

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIMIT_TIME_REAL` is used and expect a `int`.

Possible cli:

* --limit-time-real

== osv_memory_count_limit
Force a limit on the maximum number of records kept in the virtual osv_memory tables.
         by default there is no limit.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `OSV_MEMORY_COUNT_LIMIT` is used and expect a `int`.

Possible cli:

* --osv-memory-count-limit

== osv_memory_age_limit
Time limit (decimal value in hours) records created with a transientmodel (mostly wizard)
        are kept in the database. default to 1 hour.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `OSV_MEMORY_AGE_LIMIT` is used and expect a `float`.

Possible cli:

* --transient-age-limit

== limit_memory_hard
Maximum allowed virtual memory per worker (in bytes), when reached,
         any memory allocation will fail (default 2560mib).

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIMIT_MEMORY_HARD` is used and expect a `int`.

Possible cli:

* --limit-memory-hard

== limit_memory_soft
Maximum allowed virtual memory per worker (in bytes),
         when reached the worker be reset after the current request (default 2048mib).

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIMIT_MEMORY_SOFT` is used and expect a `int`.

Possible cli:

* --limit-memory-soft

== limit_memory_soft_gevent
Maximum allowed virtual memory per gevent worker (in bytes),
        when reached the worker will be reset after the current request. defaults to `--limit-memory-soft`.

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIMIT_MEMORY_SOFT_GEVENT` is used and expect a `int`.

Possible cli:

* --limit-memory-soft-gevent

== max_cron_threads
Maximum number of threads processing concurrently cron jobs (default 2).

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `MAX_CRON_THREADS` is used and expect a `int`.

Possible cli:

* --max-cron-threads

== limit_time_worker_cron
Maximum time a cron thread/worker stays alive before it is restarted. set to 0 to disable. (default: 0)

TIP: Supported Odoo version from 11.0 until 18.0

The environment variable `LIMIT_TIME_WORKER_CRON` is used and expect a `int`.

Possible cli:

* --limit-time-worker-cron



== Other keys
