= OCA: queue_job Configuration

The converter `ConfigConverterQueueJob` allow to convert environment variable related to oca: queue_job configuration to valid odoo CLI.

include::partial$oca_queue_job.adoc[]




== Other keys


=== QUEUE_JOB_ENABLE
NOTE: Convert environ key=queue_job_enable to <object object at 0x78756c55d420>

The environment variable `QUEUE_JOB_ENABLE` is used and expect a `bool`.

=== ODOO_QUEUE_JOB_CHANNELS
NOTE: Convert environ key=odoo_queue_job_channels to env_channels

The environment variable `ODOO_QUEUE_JOB_CHANNELS` is used and expect a `set`.

=== QUEUE_JOB_CHANNELS
NOTE: Convert environ key=queue_job_channels to channels

The environment variable `QUEUE_JOB_CHANNELS` is used and expect a `set`.

=== QUEUE_JOB_SCHEME
NOTE: Convert environ key=queue_job_scheme to scheme

The environment variable `QUEUE_JOB_SCHEME` is used and expect a `str`.

=== QUEUE_JOB_HOST
NOTE: Convert environ key=queue_job_host to host

The environment variable `QUEUE_JOB_HOST` is used and expect a `str`.

=== QUEUE_JOB_PORT
NOTE: Convert environ key=queue_job_port to port

The environment variable `QUEUE_JOB_PORT` is used and expect a `int`.

=== QUEUE_JOB_HTTP_AUTH_USER
NOTE: Convert environ key=queue_job_http_auth_user to http_auth_user

The environment variable `QUEUE_JOB_HTTP_AUTH_USER` is used and expect a `str`.

=== QUEUE_JOB_HTTP_AUTH_PASSWORD
NOTE: Convert environ key=queue_job_http_auth_password to http_auth_password

The environment variable `QUEUE_JOB_HTTP_AUTH_PASSWORD` is used and expect a `str`.

=== QUEUE_JOB_JOBRUNNER_DB_HOST
NOTE: Convert environ key=queue_job_jobrunner_db_host to jobrunner_db_host

The environment variable `QUEUE_JOB_JOBRUNNER_DB_HOST` is used and expect a `str`.

=== QUEUE_JOB_JOBRUNNER_DB_PORT
NOTE: Convert environ key=queue_job_jobrunner_db_port to jobrunner_db_port

The environment variable `QUEUE_JOB_JOBRUNNER_DB_PORT` is used and expect a `int`.

=== QUEUE_JOB_JOBRUNNER_DB_PORT
NOTE: Convert environ key=queue_job_jobrunner_db_port to jobrunner_db_user

The environment variable `QUEUE_JOB_JOBRUNNER_DB_PORT` is used and expect a `str`.

=== QUEUE_JOB_JOBRUNNER_DB_PORT
NOTE: Convert environ key=queue_job_jobrunner_db_port to jobrunner_db_password

The environment variable `QUEUE_JOB_JOBRUNNER_DB_PORT` is used and expect a `str`.
