= Update or Install Configuration

The converter `ConfigConverterUpdateInit` allow to convert environment variable related to update or install configuration to valid odoo CLI.

include::partial$update_init.adoc[]


== install
NOTE: Install odoo modules. with `Possible cli:

* -i
* --init`

The environment variable `INSTALL` is repeatable.
This mean a suffix can be added after an **single** `_`. For example `INSTALL_value`, the suffix is `value` not `_value`

The behavior depends of the value.

* If the value is "True" then the suffix is used.
* If the value is "False" then value is discard
* If the value is not a boolean (int, float, string, csv) then the suffix is taken has value.

[,shell]
----
INSTALL="v1,v2" # <.>
INSTALL_0="v0,bar" # <.>
INSTALL_1="1" # <.>
INSTALL_FOO="True" # <.>
INSTALL_XX="bar" # <.>
----
<.> Classic csv value
<.> csv value : don't use the suffix
<.> Not a boolean value : use the value
<.> Boolean value: The suffix `FOO` is used
<.> Not a boolean value : use the value

The result (the order is not constant) will be ["v1", "v2", "v0", "foo", "bar"].

NOTE: Like csv value, all the value are deduplicated


== update
NOTE: Update odoo modules. with `Possible cli:

* -u
* --update`

The environment variable `UPDATE` is repeatable.
This mean a suffix can be added after an **single** `_`. For example `UPDATE_value`, the suffix is `value` not `_value`

The behavior depends of the value.

* If the value is "True" then the suffix is used.
* If the value is "False" then value is discard
* If the value is not a boolean (int, float, string, csv) then the suffix is taken has value.

[,shell]
----
UPDATE="v1,v2" # <.>
UPDATE_0="v0,bar" # <.>
UPDATE_1="1" # <.>
UPDATE_FOO="True" # <.>
UPDATE_XX="bar" # <.>
----
<.> Classic csv value
<.> csv value : don't use the suffix
<.> Not a boolean value : use the value
<.> Boolean value: The suffix `FOO` is used
<.> Not a boolean value : use the value

The result (the order is not constant) will be ["v1", "v2", "v0", "foo", "bar"].

NOTE: Like csv value, all the value are deduplicated


== upgrade_path
NOTE: Specify an additional upgrade path. with `Possible cli:

* --upgrade-path`

The environment variable `UPGRADE_PATH` is repeatable.
This mean a suffix can be added after an **single** `_`. For example `UPGRADE_PATH_value`, the suffix is `value` not `_value`

The behavior depends of the value.

* If the value is "True" then the suffix is used.
* If the value is "False" then value is discard
* If the value is not a boolean (int, float, string, csv) then the suffix is taken has value.

[,shell]
----
UPGRADE_PATH="v1,v2" # <.>
UPGRADE_PATH_0="v0,bar" # <.>
UPGRADE_PATH_1="1" # <.>
UPGRADE_PATH_FOO="True" # <.>
UPGRADE_PATH_XX="bar" # <.>
----
<.> Classic csv value
<.> csv value : don't use the suffix
<.> Not a boolean value : use the value
<.> Boolean value: The suffix `FOO` is used
<.> Not a boolean value : use the value

The result (the order is not constant) will be ["v1", "v2", "v0", "foo", "bar"].

NOTE: Like csv value, all the value are deduplicated




== Other keys


=== PRE_UPGRADE_SCRIPTS
NOTE: Run specific upgrade scripts before loading any module when -u is provided.

The environment variable `PRE_UPGRADE_SCRIPTS` is used and expect a `set`.
