= Server wide module Configuration

The converter `ConfigConverterServerWideModule` allow to convert environment variable related to server wide module configuration to valid odoo CLI.

include::partial$wide_modules.adoc[]


== server_wide_modules
NOTE: List of server-wide modules. with `Possible cli:

* --load`

The environment variable `LOAD` is repeatable.
This mean a suffix can be added after an **single** `_`. For example `LOAD_value`, the suffix is `value` not `_value`

The behavior depends of the value.

* If the value is "True" then the suffix is used.
* If the value is "False" then value is discard
* If the value is not a boolean (int, float, string, csv) then the suffix is taken has value.

[,shell]
----
LOAD="v1,v2" # <.>
LOAD_0="v0,bar" # <.>
LOAD_1="1" # <.>
LOAD_FOO="True" # <.>
LOAD_XX="bar" # <.>
----
<.> Classic csv value
<.> csv value : don't use the suffix
<.> Not a boolean value : use the value
<.> Boolean value: The suffix `FOO` is used
<.> Not a boolean value : use the value

The result (the order is not constant) will be ["v1", "v2", "v0", "foo", "bar"].

NOTE: Like csv value, all the value are deduplicated




== Other keys


=== SERVER_WIDE_MODULES
NOTE: Old version of the list of the server-wide modules

The environment variable `SERVER_WIDE_MODULES` is used and expect a `set`.
