var FuncNodesPlugin=function(S,l){"use strict";function b(o){const d=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(o){for(const e in o)if(e!=="default"){const u=Object.getOwnPropertyDescriptor(o,e);Object.defineProperty(d,e,u.get?u:{enumerable:!0,get:()=>o[e]})}}return d.default=o,Object.freeze(d)}const g=b(S);var _={exports:{}},m={};/**
 * @license React
 * react-jsx-runtime.production.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var h;function O(){if(h)return m;h=1;var o=Symbol.for("react.transitional.element"),d=Symbol.for("react.fragment");function e(u,t,s){var v=null;if(s!==void 0&&(v=""+s),t.key!==void 0&&(v=""+t.key),"key"in t){s={};for(var f in t)f!=="key"&&(s[f]=t[f])}else s=t;return t=s.ref,{$$typeof:o,type:u,key:v,ref:t!==void 0?t:null,props:s}}return m.Fragment=d,m.jsx=e,m.jsxs=e,m}var y;function j(){return y||(y=1,_.exports=O()),_.exports}var R=j();return{renderpluginfactory:({})=>({handle_preview_renderers:{},data_overlay_renderers:{},data_preview_renderers:{},data_view_renderers:{},input_renderers:{},node_hooks:{"webcam.browserwebcam":[({})=>{const[e,u]=g.useState(null),t=l.useIOValueStore("delay_ms"),s=l.useIOValueStore("quality"),v=l.useIOValueStore("src"),f=l.useSetIOValue("imagedata"),x=l.useSetIOValueOptions("src");return g.useEffect(()=>{async function p(){const r=v?.preview?.value;if(r==null||r==="null"){u(null);return}try{u(await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:r.toString()}}}))}catch(a){console.error("Error accessing webcam:",a),u(null)}}return p(),()=>{e&&e.getTracks().forEach(r=>r.stop())}},[v]),g.useEffect(()=>{async function p(){await navigator.mediaDevices.getUserMedia({video:!0});const r=await navigator.mediaDevices.enumerateDevices(),a=[],c=[];for(var n=0;n<r.length;n++){var i=r[n];i.kind==="videoinput"&&(a.push(i.deviceId),c.push(i.label||"camera "+(n+1)))}x({values:a,keys:c,nullable:!0})}p()},[x]),g.useEffect(()=>{if(!e)return;const p=s?.preview,r=t?.preview;if(p===void 0||r===void 0)return;let a=parseFloat((p.value??70).toString());isNaN(a)&&(a=70),a<0&&(a=0),a>100&&(a=100);let c=parseFloat((r.value??1e3).toString());isNaN(c)&&(c=1e3),c<0&&(c=0);const n=document.createElement("video");n.srcObject=e,n.play().catch(()=>{});const i=document.createElement("canvas"),k=setInterval(async()=>{i.width=n.videoWidth,i.height=n.videoHeight;const E=i.getContext("2d");E&&(E.drawImage(n,0,0,i.width,i.height),i.toBlob(async w=>{if(!w)return;const I=await w.arrayBuffer(),P=new Uint8Array(I),T=btoa(P.reduce((q,F)=>q+String.fromCharCode(F),""));f({width:i.width,height:i.height,data:T},!1)},"image/jpeg",a/100))},c);return()=>{clearInterval(k),n.pause(),n.srcObject=null}},[e,s,t,f]),R.jsx(R.Fragment,{})}]}}),v:l.LATEST_VERSION}}(React,FuncNodesReactFlow);
