def get_current_traceparent() -> str | None: ...
def get_trace_context_info() -> dict[str, str] | None: ...
def format_traceparent(trace_id: str, span_id: str, sampled: bool = True) -> str: ...
def parse_traceparent(traceparent: str) -> dict[str, str] | None: ...
