import pandas as pd
from ._log_entry import LogEntry as LogEntry
from ._log_level import LogLevel as LogLevel
from rich.table import Table

class Log(list[LogEntry]):
    MAX_RECORDS: int
    def show(self) -> None: ...
    def __rich__(self) -> Table: ...
    def to_dataframe(self) -> pd.DataFrame: ...
    @staticmethod
    def tail(max_records: int | None = None) -> Log: ...
    @staticmethod
    def get(solas_id: str | None = None, max_records: int | None = None, for_display: bool | None = None) -> Log: ...
