# -*- coding: utf-8 -*-

"""
twilioapiexplorer

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Created26(object):

    """Implementation of the 'Created26' model.

    Attributes:
        account_sid (str): The model property of type str.
        sid (str): The model property of type str.
        trunk_sid (str): The model property of type str.
        friendly_name (str): The model property of type str.
        date_created (str): The model property of type str.
        date_updated (str): The model property of type str.
        url (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_sid": 'account_sid',
        "sid": 'sid',
        "trunk_sid": 'trunk_sid',
        "friendly_name": 'friendly_name',
        "date_created": 'date_created',
        "date_updated": 'date_updated',
        "url": 'url'
    }

    def __init__(self,
                 account_sid=None,
                 sid=None,
                 trunk_sid=None,
                 friendly_name=None,
                 date_created=None,
                 date_updated=None,
                 url=None):
        """Constructor for the Created26 class"""

        # Initialize members of the class
        self.account_sid = account_sid 
        self.sid = sid 
        self.trunk_sid = trunk_sid 
        self.friendly_name = friendly_name 
        self.date_created = date_created 
        self.date_updated = date_updated 
        self.url = url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_sid = dictionary.get("account_sid") if dictionary.get("account_sid") else None
        sid = dictionary.get("sid") if dictionary.get("sid") else None
        trunk_sid = dictionary.get("trunk_sid") if dictionary.get("trunk_sid") else None
        friendly_name = dictionary.get("friendly_name") if dictionary.get("friendly_name") else None
        date_created = dictionary.get("date_created") if dictionary.get("date_created") else None
        date_updated = dictionary.get("date_updated") if dictionary.get("date_updated") else None
        url = dictionary.get("url") if dictionary.get("url") else None
        # Return an object of this model
        return cls(account_sid,
                   sid,
                   trunk_sid,
                   friendly_name,
                   date_created,
                   date_updated,
                   url)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'account_sid={self.account_sid!r}, '
                f'sid={self.sid!r}, '
                f'trunk_sid={self.trunk_sid!r}, '
                f'friendly_name={self.friendly_name!r}, '
                f'date_created={self.date_created!r}, '
                f'date_updated={self.date_updated!r}, '
                f'url={self.url!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'account_sid={self.account_sid!s}, '
                f'sid={self.sid!s}, '
                f'trunk_sid={self.trunk_sid!s}, '
                f'friendly_name={self.friendly_name!s}, '
                f'date_created={self.date_created!s}, '
                f'date_updated={self.date_updated!s}, '
                f'url={self.url!s})')
