# -*- coding: utf-8 -*-

"""
twilioapiexplorer

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from twilioapiexplorer.models.message_1 import Message1
from twilioapiexplorer.models.meta import Meta


class OK133(object):

    """Implementation of the 'OK133' model.

    Attributes:
        messages (List[Message1]): The model property of type List[Message1].
        meta (Meta): The model property of type Meta.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "messages": 'messages',
        "meta": 'meta'
    }

    def __init__(self,
                 messages=None,
                 meta=None):
        """Constructor for the OK133 class"""

        # Initialize members of the class
        self.messages = messages 
        self.meta = meta 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        messages = None
        if dictionary.get('messages') is not None:
            messages = [Message1.from_dictionary(x) for x in dictionary.get('messages')]
        meta = Meta.from_dictionary(dictionary.get('meta')) if dictionary.get('meta') else None
        # Return an object of this model
        return cls(messages,
                   meta)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'messages={self.messages!r}, '
                f'meta={self.meta!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'messages={self.messages!s}, '
                f'meta={self.meta!s})')
