# -*- coding: utf-8 -*-

"""
twilioapiexplorer

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from twilioapiexplorer.models.log import Log
from twilioapiexplorer.models.meta import Meta


class OK351(object):

    """Implementation of the 'OK351' model.

    Attributes:
        logs (List[Log]): The model property of type List[Log].
        meta (Meta): The model property of type Meta.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "logs": 'logs',
        "meta": 'meta'
    }

    def __init__(self,
                 logs=None,
                 meta=None):
        """Constructor for the OK351 class"""

        # Initialize members of the class
        self.logs = logs 
        self.meta = meta 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        logs = None
        if dictionary.get('logs') is not None:
            logs = [Log.from_dictionary(x) for x in dictionary.get('logs')]
        meta = Meta.from_dictionary(dictionary.get('meta')) if dictionary.get('meta') else None
        # Return an object of this model
        return cls(logs,
                   meta)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'logs={self.logs!r}, '
                f'meta={self.meta!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'logs={self.logs!s}, '
                f'meta={self.meta!s})')
