__all__ = [
    "full_version",
]

__version__: str = ...
__full_version__: str = ...
__git_short_hash__: str = ...
__git_full_hash__: str = ...
__build_timestamp__: str = ...
__ir_version__: str = ...
__ir_git_short_hash__: str = ...
__ir_build_timestamp__: str = ...

def full_version() -> str: ...
