import pandas as pd

PRODUCT_NAME: str
PRODUCT_DESCRIPTION: str
PRODUCT_URL: str
SUPPORT_EMAIL: str
DEFAULT_RANDOM_STATE: int
NAMES_DF: pd.DataFrame
N_FIRST: int
N_LAST: int
SCATTER_QUALITY_AXIS: str
SCATTER_DISPARITY_AXIS: str
COLORSCALE: str
