# -*- coding: utf-8 -*-

"""
googlemapsplatformcoreapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from googlemapsplatformcoreapis.models.end_location_4 import EndLocation4
from googlemapsplatformcoreapis.models.localized_values import LocalizedValues
from googlemapsplatformcoreapis.models.navigation_instruction import NavigationInstruction
from googlemapsplatformcoreapis.models.polyline_2 import Polyline2
from googlemapsplatformcoreapis.models.start_location_4 import StartLocation4


class Step2(object):

    """Implementation of the 'Step2' model.

    Attributes:
        distance_meters (int): The model property of type int.
        static_duration (str): The model property of type str.
        polyline (Polyline2): The model property of type Polyline2.
        start_location (StartLocation4): The model property of type
            StartLocation4.
        end_location (EndLocation4): The model property of type EndLocation4.
        navigation_instruction (NavigationInstruction): The model property of
            type NavigationInstruction.
        localized_values (LocalizedValues): The model property of type
            LocalizedValues.
        travel_mode (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "distance_meters": 'distanceMeters',
        "static_duration": 'staticDuration',
        "polyline": 'polyline',
        "start_location": 'startLocation',
        "end_location": 'endLocation',
        "navigation_instruction": 'navigationInstruction',
        "localized_values": 'localizedValues',
        "travel_mode": 'travelMode'
    }

    def __init__(self,
                 distance_meters=None,
                 static_duration=None,
                 polyline=None,
                 start_location=None,
                 end_location=None,
                 navigation_instruction=None,
                 localized_values=None,
                 travel_mode=None):
        """Constructor for the Step2 class"""

        # Initialize members of the class
        self.distance_meters = distance_meters 
        self.static_duration = static_duration 
        self.polyline = polyline 
        self.start_location = start_location 
        self.end_location = end_location 
        self.navigation_instruction = navigation_instruction 
        self.localized_values = localized_values 
        self.travel_mode = travel_mode 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        distance_meters = dictionary.get("distanceMeters") if dictionary.get("distanceMeters") else None
        static_duration = dictionary.get("staticDuration") if dictionary.get("staticDuration") else None
        polyline = Polyline2.from_dictionary(dictionary.get('polyline')) if dictionary.get('polyline') else None
        start_location = StartLocation4.from_dictionary(dictionary.get('startLocation')) if dictionary.get('startLocation') else None
        end_location = EndLocation4.from_dictionary(dictionary.get('endLocation')) if dictionary.get('endLocation') else None
        navigation_instruction = NavigationInstruction.from_dictionary(dictionary.get('navigationInstruction')) if dictionary.get('navigationInstruction') else None
        localized_values = LocalizedValues.from_dictionary(dictionary.get('localizedValues')) if dictionary.get('localizedValues') else None
        travel_mode = dictionary.get("travelMode") if dictionary.get("travelMode") else None
        # Return an object of this model
        return cls(distance_meters,
                   static_duration,
                   polyline,
                   start_location,
                   end_location,
                   navigation_instruction,
                   localized_values,
                   travel_mode)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'distance_meters={self.distance_meters!r}, '
                f'static_duration={self.static_duration!r}, '
                f'polyline={self.polyline!r}, '
                f'start_location={self.start_location!r}, '
                f'end_location={self.end_location!r}, '
                f'navigation_instruction={self.navigation_instruction!r}, '
                f'localized_values={self.localized_values!r}, '
                f'travel_mode={self.travel_mode!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'distance_meters={self.distance_meters!s}, '
                f'static_duration={self.static_duration!s}, '
                f'polyline={self.polyline!s}, '
                f'start_location={self.start_location!s}, '
                f'end_location={self.end_location!s}, '
                f'navigation_instruction={self.navigation_instruction!s}, '
                f'localized_values={self.localized_values!s}, '
                f'travel_mode={self.travel_mode!s})')
