# -*- coding: utf-8 -*-

"""
instagramapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from instagramapi.api_helper import APIHelper


class IdPaginationInfo(object):

    """Implementation of the 'IdPaginationInfo' model.

    Attributes:
        next_max_id (str): The max ID of the next page
        next_url (str): URL to retrieve next page of entries

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "next_max_id": 'next_max_id',
        "next_url": 'next_url'
    }

    _optionals = [
        'next_max_id',
        'next_url',
    ]

    def __init__(self,
                 next_max_id=APIHelper.SKIP,
                 next_url=APIHelper.SKIP):
        """Constructor for the IdPaginationInfo class"""

        # Initialize members of the class
        if next_max_id is not APIHelper.SKIP:
            self.next_max_id = next_max_id 
        if next_url is not APIHelper.SKIP:
            self.next_url = next_url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        next_max_id = dictionary.get("next_max_id") if dictionary.get("next_max_id") else APIHelper.SKIP
        next_url = dictionary.get("next_url") if dictionary.get("next_url") else APIHelper.SKIP
        # Return an object of this model
        return cls(next_max_id,
                   next_url)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'next_max_id={(self.next_max_id if hasattr(self, "next_max_id") else None)!r}, '
                f'next_url={(self.next_url if hasattr(self, "next_url") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'next_max_id={(self.next_max_id if hasattr(self, "next_max_id") else None)!s}, '
                f'next_url={(self.next_url if hasattr(self, "next_url") else None)!s})')
