from ..internal_utils.fallback_logger import fallback_logger as fallback_logger
from _typeshed import Incomplete
from datetime import timedelta as timedelta
from typing import Any

def truncate_value(value: Any, max_length: int = 1000) -> str: ...

mcp: Incomplete
LOCAL_SERVER_URL: str

def call_local_server(endpoint: str, params: dict[str, Any] | None = None) -> dict[str, Any]: ...
def recent_logs(limit: int = 50, service: str | None = None, level: str | None = None) -> str: ...
def search_logs(query: str, service: str | None = None, level: str | None = None, limit: int = 50) -> str: ...
def list_services() -> str: ...
def start_server(port: int | None = None, open_browser: bool = False) -> str: ...
def main() -> None: ...
