import argparse
from ..internal_utils.fallback_logger import fallback_logger as fallback_logger

def find_available_port(start_port: int = 8080, max_attempts: int = 10) -> int: ...
def serve_command(args: argparse.Namespace) -> None: ...
def claude_install_command(args: argparse.Namespace) -> None: ...
def claude_remove_command(args: argparse.Namespace) -> None: ...
def claude_init_command(args: argparse.Namespace) -> None: ...
def cursor_init_command(args: argparse.Namespace) -> None: ...
def main() -> None: ...
